### ISSUE TITLE
configuration file and path it

### ISSUE THREAD

**Issue by masihfathi** [zone-eu/zone-mta#164]
Hi. Where we should setup plugins config

```
  "plugins": {
    "modules/zonemta-delivery-counters": {
      "enabled": "main",
      "redis": "redis://localhost:6379/2",
      "prefix": "zmta"
    }
  }
```
in the production env, we have config folder and listed files are:
dbs-development.toml, dns.toml , dbs-production.toml ...
which file we must add plugins configuration?

**Comment by ppadron** [comment]
I think there different ways to do it, but I base myself on https://github.com/zone-eu/zone-mta-template and create one TOML file per plugin in the `config/plugins` directory. In your example, you would have `config/plugins/delivery-counters.toml` with the following content:

```toml
["modules/zonemta-delivery-counters"]
enabled=main
redis="redis://localhost:6379/2"
prefix=zmta
```
